export const Task = [
    {
        id: 1,
        name: "Email to Jones",
        category: "work",
        date: "2024-08-20",
        startTime: "08:00",
        endTime: "12:00",
        priority: "low",
        description: "hello world",
    },
    {
        id: 2,
        name: "Call Sophia",
        category: "school",
        date: "2024-08-25",
        startTime: "07:00",
        endTime: "09:00",
        priority: "high",
        description: "",
    },
    {
        id: 3,
        name: "Code till dawn",
        category: "groceries",
        date: "2024-08-22",
        startTime: "08:00",
        endTime: "12:00",
        priority: "medium",
        description: "Segun is the boss",
    },
    {
        id: 4,
        name: "Yoooo catch a break",
        category: "work",
        date: "2024-09-20",
        startTime: "10:00",
        endTime: "02:00",
        priority: "low",
        description: "hello bitch",
    },
    {
        id: 5,
        name: "Call the startup office",
        category: "school",
        date: "2024-08-29",
        startTime: "10:00",
        endTime: "02:00",
        priority: "high",
        description: "testing",
    },
];